version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  edge_client:
    build:
      context: ./edge_client
    container_name: edge_client
    restart: unless-stopped
